#!/bin/bash

git remote prune origin
git gc

# delete old coverage reports
rm -rf coverage
rm -f features/reports/*.xml
rm -f features/reports/screenshots/*.png

rvm use 1.9.2
bundle install --path vendor/bundle

# start cucumber on Xvfb
export DISPLAY=:91
script/xvfb start
bundle exec cucumber features --format Cucumber::Formatter::Junit --out features/reports --format pretty
RESULT=$?
script/xvfb stop
exit $RESULT
