/*
 * File: MyViewport.ui.js
 * Date: Tue Sep 14 2010 19:45:23 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                region: 'west',
                split: true,
                xtype: 'rwiki.treepanel'
            },
            {
                region: 'center',
                xtype: 'mypanel'
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
