/*
 * File: MyViewport.ui.js
 * Date: Mon Sep 13 2010 18:01:12 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'treepanel',
                title: 'Pages',
                region: 'west',
                width: 167,
                split: true,
                collapsible: true,
                root: {
                    text: 'Tree Node'
                },
                loader: {

                }
            },
            {
                xtype: 'panel',
                region: 'center',
                layout: 'border',
                items: [
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        region: 'center',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Tab 1'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'My Panel',
                        region: 'south',
                        width: 100,
                        collapsible: true,
                        items: [
                            {
                                xtype: 'container',
                                height: 400
                            }
                        ]
                    }
                ]
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
