/*
 * File: Rwiki.TabPanel.ui.js
 * Date: Tue Sep 14 2010 19:45:23 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Rwiki');
Rwiki.TabPanelUi = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    initComponent: function() {
        this.items = [
            {
                xtype: 'rwiki.tabpanel.pagetab'
            },
            {
                xtype: 'rwiki.tabpanel.pagetab'
            }
        ];
        Rwiki.TabPanelUi.superclass.initComponent.call(this);
    }
});
