/*
 * File: Rwiki.TabPane.PageTab.ui.js
 * Date: Tue Sep 14 2010 19:45:23 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Rwiki.TabPane');
Rwiki.TabPane.PageTabUi = Ext.extend(Ext.Panel, {
    title: 'Page name',
    initComponent: function() {
        Rwiki.TabPane.PageTabUi.superclass.initComponent.call(this);
    }
});
