/*
 * File: Rwiki.MainPanel.ui.js
 * Date: Mon Sep 13 2010 18:09:47 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Rwiki');
Rwiki.MainPanelUi = Ext.extend(Ext.Panel, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                region: 'center',
                xtype: 'rwiki.tabpanel'
            },
            {
                region: 'south',
                xtype: 'rwiki.editorpanel'
            }
        ];
        Rwiki.MainPanelUi.superclass.initComponent.call(this);
    }
});
