/*
 * File: Rwiki.TabPanel.ui.js
 * Date: Mon Sep 13 2010 18:09:47 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Rwiki');
Rwiki.TabPanelUi = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Page name'
            }
        ];
        Rwiki.TabPanelUi.superclass.initComponent.call(this);
    }
});
