/*
 * File: Rwiki.TreePanel.ui.js
 * Date: Tue Sep 14 2010 19:45:23 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Rwiki');
Rwiki.TreePanelUi = Ext.extend(Ext.tree.TreePanel, {
    title: 'Pages',
    width: 200,
    collapsible: true,
    initComponent: function() {
        this.root = {
            text: 'Tree Node'
        };
        this.loader = {

        };
        Rwiki.TreePanelUi.superclass.initComponent.call(this);
    }
});
