/*
 * File: xds_index.js
 * Date: Mon Sep 13 2010 18:09:47 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new Rwiki.Viewport({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
