#!/bin/bash
source ~/.bashrc

git remote prune origin
git gc

export WORKING_PATH=$(pwd)
export DISPLAY=:92

rvm use 1.9.2
bundle install --path vendor/bundle
script/xvfb start

bundle exec rake jasmine:ci --trace
RESULT=$?

script/xvfb stop
exit $RESULT
