#!/bin/bash

if [ -n $WORKING_PATH ] ; then
  export WORKING_PATH=$(pwd)
fi

SELENIUM_SERVER_PORT=4444
SELENIUM_JAR="${WORKING_PATH}/vendor/bundle/ruby/1.9.1/gems/selenium-rc-2.2.4/vendor/selenium-server.jar"

DEAMON="/usr/bin/java"
DAEMON_ARGS="-jar ${SELENIUM_JAR} -port ${SELENIUM_SERVER_PORT}"

PIDFILE="/tmp/selenium_${SELENIUM_SERVER_PORT}.pid"

case "$1" in
  start)
    process_id=$(lsof -i tcp:$SELENIUM_SERVER_PORT -Fp|tr -d p)
    if [ $process_id ] ; then
      echo -n "Selenium server is already running"
    else
      echo -n "Starting Selenium"
      /sbin/start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $DEAMON -- $DAEMON_ARGS 
    fi
    echo "."
    ;;
  stop)
    echo -n "Stopping Selenium"
    /sbin/start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
  echo "Usage: /etc/init.d/selenium {start|stop|restart}"
  exit 1
esac
exit 0
