/*
 * File: Rwiki.TabPane.PageTab.js
 * Date: Tue Sep 14 2010 19:44:14 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Rwiki.TabPane.PageTab = Ext.extend(Rwiki.TabPane.PageTabUi, {
    initComponent: function() {
        Rwiki.TabPane.PageTab.superclass.initComponent.call(this);
    }
});
Ext.reg('rwiki.tabpanel.pagetab', Rwiki.TabPane.PageTab);